### ISSUE TITLE
Add to Chrome Web Store

### ISSUE THREAD

**Issue by csu** [wilbertliu/Mata#3]
If you haven't already, could you add this to the Play store and include a link in the Readme?

**Comment by ghost** [comment]
You mean the [Chrome Web Store](https://chrome.google.com/webstore/category/apps)?

**Comment by csu** [comment]
Whoops, yeah

**Comment by metacoin** [comment]
or at least put install instructions in the README...

**Comment by csu** [comment]
:+1: ^

**Comment by ghost** [comment]
I added install instructions to the README, just waiting for the owner to merge. Take a look at my [fork](https://github.com/idriskhenchil/Mata) for now if you'd like, it has instructions :)

**Comment by wilbertliu** [comment]
Done!

Kudos to what Idris has done. Added installation instruction on the readme.

👌

**Comment by iamcaner** [comment]
+1

**Comment by ghost** [comment]
Mata has been added to the [Chrome Web Store](https://chrome.google.com/webstore/detail/mata/oakhnpcgdembaopakdnfkejfcaeipeik?hl=en-US)! Thanks @onesneakymofo

**Comment by wilbertliu** [comment]
Insane! Thanks @idriskhenchil and the man @onesneakymofo 👏🏽
