### ISSUE TITLE
Does not work on Chrome OS

### ISSUE THREAD

**Issue by onesneakymofo** [wilbertliu/Mata#5]
Whenever I drag and drop into the Externsions settings, I get the following error:

```Package is invalid: 'CRX_MAGIC_NUMBER_INVALID'.

**Comment by wilbertliu** [comment]
Hmm, any idea for this @oelmekki @idriskhenchil @luruke?
I've tried to google it out, but didn't find any clue.

**Comment by onesneakymofo** [comment]
I'm closing this, @wilbertliu.  I figured out the issue.  I'm creating a Chrome Extension for the Chrome App store right now.  I'll send you the link once it's finished.

**Comment by wilbertliu** [comment]
Cool @onesneakymofo! 👍🏽

If you don't mind, you could share your approach to solve this problem,
so people could also learn something.

Thanks! 😀

**Comment by onesneakymofo** [comment]
Yeah, I was downloading the .crx file that was attached to the project.  I ended up just downloading the entire project and recreating the .crx.  It'll be on the Chrome Web Store tomorrow.

**Comment by wilbertliu** [comment]
Wow, great man!
Many thanks! :)

**Comment by oelmekki** [comment]
Hi,

Nice to see it already fixed :)

Btw, be aware that [crx install won't be an option for long](https://developer.chrome.com/extensions/hosting).

**Comment by ghost** [comment]
Yeah I'd stay away from crx honestly, I just added it because very few people would of known how to install this manually and it would of been a shame if they weren't able to try Mata. I'm glad it's going to the Chrome Web Store though!
