### ISSUE TITLE
Night only

### ISSUE THREAD

**Issue by BlackStoneD** [wilbertliu/Mata#9]
Hello
Thank you to add new very usefull feature in chrome
When I active Mata in chrome Version 63.0.3239.40 (Build officiel) beta (64 bits), and I try to use desktop chrome://apps/ feedly (in separate window) Feedly is black when chrome is white.
Thank you to suggest a solution or workaround sinc I hav to de-activate Mata.
regards
BlackStoneD

**Comment by wilbertliu** [comment]
Hey @BlackStoneD,
I'm not sure I understand what you mean. Could you please elaborate more?
Thanks!

**Comment by BlackStoneD** [comment]
because my english is not fluent I try again
I use chrome Version 63.0.3239.40 (Build officiel) beta (64 bits),
I use Feedly as a chrome application in a different window.
I use Twitter as a chrome application in a different window.
When Mata extension is activated in chrome with no action on the bar icon (deactivated, day mode), Feedly windows is displayed systematically as if it is night activated but Twitter window is displayed regularly.
When Mata icon is activated (night chrome mode) no action on feedly window still night mode and Twitter window is displayed regularly (night mode)

**Comment by wilbertliu** [comment]
@BlackStoneD No problem man, no one is perfect. 🙂

Anyway, could you please try to open any other page (let's say google or something), and see whether Mata performs correctly? If there's no problem with other pages, then I suspect the dark theme that you saw on Feedly comes from them, not the Mata extension.

**Comment by wilbertliu** [comment]
Closing this issue due to no response from the author.
